[tools]
lua = "latest"
lua-language-server = "latest"

[tasks.test]
description = "Run tensor tests"
run = "busted --helper test/helper.lua test"

[tasks.main]
description = "Run the tensor example"
run = "lua lua/main.lua"
