[tools]
lua = "latest"
lua-language-server = "latest"

[tasks.test]
description = "Run the tensor test suite (Fennel implementation)"
run = "busted --helper test/helper.lua test"

[tasks.main]
description = "Run the tensor example"
run = "fennel fnl/example.fnl"
